#! /usr/bin/env ruby
# frozen_string_literal: true

# copy `description` from the xmp file to the given file
#
# - each file must have a .xmp with the same root filename
#
# ## example
#
# ```
# copy-caption-from-xmp-to-video *.mov
# ```

require 'shellwords'

ARGV.each do |file|
  ext = File.extname(file)
  base = File.basename(file, ext)
  xmp = "#{base}.xmp"

  unless File.exist?(file)
    warn "WARNING: #{file.shellescape} is not a file"
    next
  end
  unless File.exist?(xmp)
    warn "WARNING: #{xmp.shellescape} is not a file"
    next
  end

  match = File.read(xmp).match(%r{description>(.*)</})
  unless match
    warn "INFO: no description in #{xmp.shellescape}"
    next
  end
  description = match[1]

  `exiftool -overwrite_original -description=#{description.shellescape} #{file.shellescape}`
  unless $? == 0
    warn "WARN: unable to add description to #{file.shellescape}"
    next
  end
end
