#! /usr/bin/env ruby
# frozen_string_literal: true

# copy `description` from the xmp file to the given file
#
# the xmp file used is
# - the xmp file with the same root filename
# - or if that doesn't exist, but the filename root looks like "IMG_E0011", then
#   the xmp file that looks like "IMG_0011"
#
# ## example
#
# ```
# copy-caption-from-xmp-to-video *.mov
# ```

require 'shellwords'

ARGV.each do |file|
  unless File.exist?(file)
    warn "WARNING: #{file.shellescape} is not a file"
    next
  end

  ext = File.extname(file)
  base = File.basename(file, ext)

  xmp = "#{base}.xmp"
  if !File.exist?(xmp) && (match = base.match(/IMG_[[:alpha:]]+([[:digit:]]+)/))
    xmp = "IMG_#{match[1]}.xmp"
  end
  unless File.exist?(xmp)
    warn "WARNING: #{xmp.shellescape} is not a file"
    next
  end

  match = File.read(xmp).match(%r{description>(.*)</})
  unless match
    warn "INFO: no description in #{xmp.shellescape}"
    next
  end
  description = match[1]

  `exiftool -preserve -overwrite_original -description=#{description.shellescape} #{file.shellescape}`
  unless $? == 0
    warn "WARN: unable to add description to #{file.shellescape}"
    next
  end
end
