#! /usr/bin/env python3

import os
import re
import shutil
import subprocess


def run(command):
    out = subprocess.run(command, check=True, capture_output=True, text=True)
    return out.stdout.strip()

def get_date(path):
    out = run([os.path.join(os.path.dirname(__file__), 'get-date'), path])
    return out


if __name__ == '__main__':
    with open('./_rename.txt', 'w') as log:
        for root,dirs,files in os.walk('.', topdown=True):
            ds = []
            for d in dirs:
                if d[0] in ('.', '-', '_',):
                    pass
                else:
                    ds.append(d)
            dirs[:] = ds

            fs = []
            for f in files:
                if f[0] in ('.', '-', '_',):
                    pass
                elif re.match(r'([0-9]{8})[^0-9]([0-9]{6})', f):
                    pass
                else:
                    fs.append(f)
            files[:] = fs

            for f in files:
                path = os.path.join(root, f)
                dest = os.path.join(root, get_date(path)+'__'+f)

                print(path, '->', dest, file=log)
                shutil.move(path, dest)

